// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyYOYzzxxxEblvNX3GR_KtUNk7AtMuAEc',
    appId: '1:469434703070:web:84ce52f4e1eef40472364f',
    messagingSenderId: '469434703070',
    projectId: 'contact-manager-9feff',
    authDomain: 'contact-manager-9feff.firebaseapp.com',
    storageBucket: 'contact-manager-9feff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFQNwiVPBTz8_-ccOREG9KHcN2b3wjD1g',
    appId: '1:469434703070:android:fe16301ec3e8212e72364f',
    messagingSenderId: '469434703070',
    projectId: 'contact-manager-9feff',
    storageBucket: 'contact-manager-9feff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ucbtAza1lr6EqN0Kmx0iLAfS1wHvQLQ',
    appId: '1:469434703070:ios:4c551d2dcdc78d0372364f',
    messagingSenderId: '469434703070',
    projectId: 'contact-manager-9feff',
    storageBucket: 'contact-manager-9feff.appspot.com',
    androidClientId: '469434703070-0kmah3iq1ub9pjrb4a2u5u2j7fpnvtdq.apps.googleusercontent.com',
    iosClientId: '469434703070-cbjjf0ilrkg7622k2iqv056e9tf3gpor.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactmanager',
  );
}
